// The starter catalogue. It is data, not code: add to it freely, and expect the
// two users to keep adding from inside the app. `defaultUnit` is the unit that
// pre-fills a recipe row; null means the entry is normally counted. Aisles must
// be values from AISLE_ORDER in lib/aisles.ts.
//
// Every entry here is an ingredient and none sets `kind`, which therefore takes
// the column's INGREDIENT default. Seeding a product means adding the field.
export const INGREDIENTS: {
  name: string
  defaultUnit: string | null
  aisle: string
}[] = [
  { name: "carote", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "funghi", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "insalata", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "limoni", defaultUnit: null, aisle: "ortofrutta" },
  { name: "melanzane", defaultUnit: null, aisle: "ortofrutta" },
  { name: "patate", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "peperoni", defaultUnit: null, aisle: "ortofrutta" },
  { name: "pomodori", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "pomodorini", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "sedano", defaultUnit: "gambo", aisle: "ortofrutta" },
  { name: "spinaci", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "zucchine", defaultUnit: null, aisle: "ortofrutta" },
  { name: "mele", defaultUnit: null, aisle: "ortofrutta" },
  { name: "banane", defaultUnit: null, aisle: "ortofrutta" },
  { name: "arance", defaultUnit: null, aisle: "ortofrutta" },
  { name: "cetrioli", defaultUnit: null, aisle: "ortofrutta" },
  { name: "pere", defaultUnit: null, aisle: "ortofrutta" },
  { name: "pesche", defaultUnit: null, aisle: "ortofrutta" },
  { name: "melone", defaultUnit: null, aisle: "ortofrutta" },
  { name: "valeriana", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "rucola", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "lattughino", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "finocchi", defaultUnit: null, aisle: "ortofrutta" },
  { name: "fagiolini", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "asparagi", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "cime di rapa", defaultUnit: "g", aisle: "ortofrutta" },

  { name: "pane", defaultUnit: "g", aisle: "panetteria" },
  { name: "piadine", defaultUnit: null, aisle: "panetteria" },
  { name: "panini", defaultUnit: null, aisle: "panetteria" },
  { name: "crostini", defaultUnit: null, aisle: "panetteria" },
  { name: "grissini", defaultUnit: null, aisle: "panetteria" },
  { name: "pasta sfoglia", defaultUnit: "rotolo", aisle: "panetteria" },
  { name: "pasta brisée", defaultUnit: "rotolo", aisle: "panetteria" },

  { name: "petto di pollo", defaultUnit: "g", aisle: "macelleria" },
  { name: "cosce di pollo", defaultUnit: "g", aisle: "macelleria" },
  { name: "macinato di manzo", defaultUnit: "g", aisle: "macelleria" },
  { name: "salsiccia", defaultUnit: "g", aisle: "macelleria" },
  { name: "fettine di vitello", defaultUnit: "g", aisle: "macelleria" },

  { name: "gamberi", defaultUnit: "g", aisle: "pescheria" },
  { name: "salmone", defaultUnit: "g", aisle: "pescheria" },
  { name: "orata", defaultUnit: null, aisle: "pescheria" },

  { name: "prosciutto crudo", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "prosciutto cotto", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "speck", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "guanciale", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "pancetta", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "bresaola", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "fesa di tacchino", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "parmigiano", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "pecorino", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "mozzarella", defaultUnit: null, aisle: "salumi e formaggi" },
  { name: "burrata", defaultUnit: null, aisle: "salumi e formaggi" },
  { name: "burratina", defaultUnit: null, aisle: "salumi e formaggi" },
  { name: "philadelphia", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "ricotta", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "gorgonzola", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "scamorza affumicata", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "scamorza dolce", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "feta", defaultUnit: "g", aisle: "salumi e formaggi" },

  { name: "uova", defaultUnit: null, aisle: "banco frigo" },
  { name: "latte", defaultUnit: "ml", aisle: "banco frigo" },
  { name: "panna da cucina", defaultUnit: "ml", aisle: "banco frigo" },
  { name: "burro", defaultUnit: "g", aisle: "banco frigo" },
  { name: "yogurt bianco", defaultUnit: "g", aisle: "banco frigo" },
  { name: "fiocchi di latte", defaultUnit: "g", aisle: "banco frigo" },
  { name: "formaggio spalmabile", defaultUnit: "g", aisle: "banco frigo" },
  { name: "hummus", defaultUnit: "g", aisle: "banco frigo" },
  { name: "salmone affumicato", defaultUnit: "g", aisle: "banco frigo" },
  { name: "straccetti veggie", defaultUnit: "g", aisle: "banco frigo" },
  { name: "hamburger veggie", defaultUnit: null, aisle: "banco frigo" },

  { name: "hamburger veggie surgelati", defaultUnit: null, aisle: "surgelati" },
  { name: "piselli surgelati", defaultUnit: "g", aisle: "surgelati" },
  { name: "spinaci surgelati", defaultUnit: "g", aisle: "surgelati" },
  { name: "gelato", defaultUnit: "g", aisle: "surgelati" },

  { name: "pasta", defaultUnit: "g", aisle: "dispensa" },
  { name: "spaghetti", defaultUnit: "g", aisle: "dispensa" },
  { name: "penne", defaultUnit: "g", aisle: "dispensa" },
  { name: "fusilli", defaultUnit: "g", aisle: "dispensa" },
  { name: "riso", defaultUnit: "g", aisle: "dispensa" },
  { name: "farro", defaultUnit: "g", aisle: "dispensa" },
  { name: "cous cous", defaultUnit: "g", aisle: "dispensa" },
  { name: "farina 00", defaultUnit: "g", aisle: "dispensa" },
  { name: "zucchero", defaultUnit: "g", aisle: "dispensa" },
  { name: "sale", defaultUnit: "g", aisle: "dispensa" },
  { name: "pepe nero", defaultUnit: "g", aisle: "dispensa" },
  { name: "olio extravergine di oliva", defaultUnit: "ml", aisle: "dispensa" },
  { name: "aceto balsamico", defaultUnit: "ml", aisle: "dispensa" },
  { name: "passata di pomodoro", defaultUnit: "ml", aisle: "dispensa" },
  { name: "pomodorini secchi", defaultUnit: "g", aisle: "dispensa" },
  { name: "olive nere", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "capperi", defaultUnit: "g", aisle: "dispensa" },
  { name: "tonno in scatola", defaultUnit: "lattina", aisle: "dispensa" },
  { name: "sgombro in scatola", defaultUnit: "lattina", aisle: "dispensa" },
  { name: "mais", defaultUnit: "lattina", aisle: "dispensa" },
  { name: "pesto", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "ceci", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "fagioli borlotti", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "lenticchie", defaultUnit: "g", aisle: "dispensa" },
  { name: "brodo vegetale", defaultUnit: "ml", aisle: "dispensa" },
  { name: "lievito di birra", defaultUnit: "bustina", aisle: "dispensa" },
  { name: "lievito per dolci", defaultUnit: "bustina", aisle: "dispensa" },
  { name: "cioccolato fondente", defaultUnit: "g", aisle: "dispensa" },
  { name: "mandorle", defaultUnit: "g", aisle: "dispensa" },
  { name: "pinoli", defaultUnit: "g", aisle: "dispensa" },
  { name: "miele", defaultUnit: "g", aisle: "dispensa" },

  { name: "vino bianco", defaultUnit: "ml", aisle: "bevande" },
  { name: "vino rosso", defaultUnit: "ml", aisle: "bevande" },
  { name: "birra", defaultUnit: "ml", aisle: "bevande" },
]
