// The starter catalogue. It is data, not code: add to it freely, and expect the
// two users to keep adding from inside the app. `defaultUnit` is the unit that
// pre-fills a recipe row; null means the ingredient is normally counted.
// Aisles must be values from AISLE_ORDER in lib/aisles.ts.
export const INGREDIENTS: {
  name: string
  defaultUnit: string | null
  aisle: string
}[] = [
  { name: "aglio", defaultUnit: "spicchio", aisle: "ortofrutta" },
  { name: "basilico", defaultUnit: "foglia", aisle: "ortofrutta" },
  { name: "carote", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "cipolla", defaultUnit: null, aisle: "ortofrutta" },
  { name: "funghi champignon", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "insalata", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "limoni", defaultUnit: null, aisle: "ortofrutta" },
  { name: "melanzane", defaultUnit: null, aisle: "ortofrutta" },
  { name: "patate", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "peperoni", defaultUnit: null, aisle: "ortofrutta" },
  { name: "pomodori", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "pomodorini", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "prezzemolo", defaultUnit: "mazzetto", aisle: "ortofrutta" },
  { name: "rosmarino", defaultUnit: "rametto", aisle: "ortofrutta" },
  { name: "salvia", defaultUnit: "foglia", aisle: "ortofrutta" },
  { name: "sedano", defaultUnit: "gambo", aisle: "ortofrutta" },
  { name: "spinaci", defaultUnit: "g", aisle: "ortofrutta" },
  { name: "zucchine", defaultUnit: null, aisle: "ortofrutta" },
  { name: "mele", defaultUnit: null, aisle: "ortofrutta" },
  { name: "banane", defaultUnit: null, aisle: "ortofrutta" },
  { name: "arance", defaultUnit: null, aisle: "ortofrutta" },

  { name: "pane", defaultUnit: "g", aisle: "panetteria" },
  { name: "pane grattugiato", defaultUnit: "g", aisle: "panetteria" },
  { name: "piadine", defaultUnit: null, aisle: "panetteria" },
  { name: "pasta sfoglia", defaultUnit: "rotolo", aisle: "panetteria" },
  { name: "pasta brisée", defaultUnit: "rotolo", aisle: "panetteria" },

  { name: "petto di pollo", defaultUnit: "g", aisle: "macelleria" },
  { name: "cosce di pollo", defaultUnit: "g", aisle: "macelleria" },
  { name: "macinato di manzo", defaultUnit: "g", aisle: "macelleria" },
  { name: "salsiccia", defaultUnit: "g", aisle: "macelleria" },
  { name: "arista di maiale", defaultUnit: "g", aisle: "macelleria" },
  { name: "fettine di vitello", defaultUnit: "g", aisle: "macelleria" },

  { name: "gamberi", defaultUnit: "g", aisle: "pescheria" },
  { name: "salmone", defaultUnit: "g", aisle: "pescheria" },
  { name: "orata", defaultUnit: null, aisle: "pescheria" },
  { name: "vongole", defaultUnit: "g", aisle: "pescheria" },
  { name: "calamari", defaultUnit: "g", aisle: "pescheria" },

  { name: "prosciutto crudo", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "prosciutto cotto", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "speck", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "guanciale", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "pancetta", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "parmigiano", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "pecorino", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "mozzarella", defaultUnit: null, aisle: "salumi e formaggi" },
  { name: "burrata", defaultUnit: null, aisle: "salumi e formaggi" },
  { name: "philadelphia", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "ricotta", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "gorgonzola", defaultUnit: "g", aisle: "salumi e formaggi" },
  { name: "scamorza", defaultUnit: "g", aisle: "salumi e formaggi" },

  { name: "uova", defaultUnit: null, aisle: "banco frigo" },
  { name: "latte", defaultUnit: "ml", aisle: "banco frigo" },
  { name: "panna da cucina", defaultUnit: "ml", aisle: "banco frigo" },
  { name: "burro", defaultUnit: "g", aisle: "banco frigo" },
  { name: "yogurt bianco", defaultUnit: "g", aisle: "banco frigo" },

  { name: "piselli surgelati", defaultUnit: "g", aisle: "surgelati" },
  { name: "spinaci surgelati", defaultUnit: "g", aisle: "surgelati" },
  { name: "gelato", defaultUnit: "g", aisle: "surgelati" },

  { name: "spaghetti", defaultUnit: "g", aisle: "dispensa" },
  { name: "penne", defaultUnit: "g", aisle: "dispensa" },
  { name: "fusilli", defaultUnit: "g", aisle: "dispensa" },
  { name: "riso", defaultUnit: "g", aisle: "dispensa" },
  { name: "riso carnaroli", defaultUnit: "g", aisle: "dispensa" },
  { name: "farina 00", defaultUnit: "g", aisle: "dispensa" },
  { name: "zucchero", defaultUnit: "g", aisle: "dispensa" },
  { name: "sale", defaultUnit: "g", aisle: "dispensa" },
  { name: "pepe nero", defaultUnit: "g", aisle: "dispensa" },
  { name: "olio extravergine di oliva", defaultUnit: "ml", aisle: "dispensa" },
  { name: "aceto balsamico", defaultUnit: "ml", aisle: "dispensa" },
  { name: "passata di pomodoro", defaultUnit: "ml", aisle: "dispensa" },
  { name: "pomodori pelati", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "pomodorini secchi", defaultUnit: "g", aisle: "dispensa" },
  { name: "olive nere", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "capperi", defaultUnit: "g", aisle: "dispensa" },
  { name: "tonno in scatola", defaultUnit: "lattina", aisle: "dispensa" },
  { name: "ceci", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "fagioli borlotti", defaultUnit: "barattolo", aisle: "dispensa" },
  { name: "lenticchie", defaultUnit: "g", aisle: "dispensa" },
  { name: "brodo vegetale", defaultUnit: "ml", aisle: "dispensa" },
  { name: "lievito di birra", defaultUnit: "bustina", aisle: "dispensa" },
  { name: "lievito per dolci", defaultUnit: "bustina", aisle: "dispensa" },
  { name: "noce moscata", defaultUnit: "g", aisle: "dispensa" },
  { name: "origano", defaultUnit: "g", aisle: "dispensa" },
  { name: "peperoncino", defaultUnit: null, aisle: "dispensa" },
  { name: "cioccolato fondente", defaultUnit: "g", aisle: "dispensa" },
  { name: "mandorle", defaultUnit: "g", aisle: "dispensa" },
  { name: "pinoli", defaultUnit: "g", aisle: "dispensa" },
  { name: "miele", defaultUnit: "g", aisle: "dispensa" },
  { name: "senape", defaultUnit: "cucchiaio", aisle: "dispensa" },

  { name: "vino bianco", defaultUnit: "ml", aisle: "bevande" },
  { name: "vino rosso", defaultUnit: "ml", aisle: "bevande" },
  { name: "acqua frizzante", defaultUnit: "l", aisle: "bevande" },
  { name: "birra", defaultUnit: "ml", aisle: "bevande" },
]
